// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efnneffbdacwcsqjkzkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbm5lZmZiZGFjd2NzcWpremtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTUwNTYsImV4cCI6MjA2MDQ5MTA1Nn0.1Eg7dbBSDJ0YoMAH9E0Z4gu3h53ircWCqCTDOs_K820";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);